// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flow_app/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LoopAdapter());
    registerAdapter(PomodoroPresetAdapter());
    registerAdapter(SessionAdapter());
    registerAdapter(SoundTypeAdapter());
    registerAdapter(TimerTypeAdapter());
    registerAdapter(UserProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LoopAdapter());
    registerAdapter(PomodoroPresetAdapter());
    registerAdapter(SessionAdapter());
    registerAdapter(SoundTypeAdapter());
    registerAdapter(TimerTypeAdapter());
    registerAdapter(UserProfileAdapter());
  }
}
